[tool.poetry]
name = "songbook2"
version = "0.1.0"
description = ""
authors = ["locho0111"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
spotipy = "^2.17.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
